### ISSUE TITLE
Have the colors default to --primary-text-color, etc

### ISSUE THREAD

**Issue by tewalds** [PolymerElements/paper-button#105]
Right now there are explicit variables for the button text color and background color, but it'd be much easier to change the theme of a site if there were variables for those and they defaulted based on --primary-color, --primary-text-color, etc.

**Comment by keanulee** [comment]
@tewalds Styling the background and text color can be done with regular CSS (without custom properties/mixins), which can already be done on a site wide basis. I don't see why we would need to introduce those variables.

```css
paper-button {
  background: red;
  color: white;
}
```

**Comment by tewalds** [comment]
That works great when the button is at the top level, but doesn't work when the buttons are within subcomponents in the shadow dom. I can do this instead:
```css
body /deep/ paper-button {
  background: red;
  color: white;
}
```
but that uses `/deep/` which is deprecated and discouraged.

I can also do:
```css
--paper-button: {
  background: red;
  color: white;
}
```
which is better. Or better yet:
```css
--paper-button: {
  background: var(--primary-background-color);
  color: var(--primary-test-color);
}
```
but why not just make that the default anyway since that's probably what most people want?
